'''
File: staff.py
Description: This module defines the Staff class and the staff subclass hierarchy used by the zoo system.
             The Staff class is a parent non-abstract class and provides shared attributes and behaviours for all
             staff members. Subclasses extend this to represent specific roles including Keeper,
             Veterinarian, and Administrator. These classes model real staff members and hold data for staff members
             in the zoo system.
Author: Borys Pierzchala
ID: 110457330
Username: PIEBY002
This is my own work as defined by the University's Academic Integrity Policy.
'''

from domain.animals.animal import Animal
from domain.records.issue import Issue


class Staff:
    class Staff:
        """ A parent class representing a generic staff member within the zoo system.
            This class provides shared attributes and behaviours for all staff roles.
            Subclasses extend this to model specific staff roles such as Keeper and Veterinarian"""

    def __init__(self, name: str, age: int, gender: str, birthday: str, id: str):
        def __init__(self, name: str, age: int, gender: str, birthday: str, id: str):
            """ Creates a Staff object and initialises shared staff attributes.
                Parameters:
                    - name: string
                        The full name of the staff member.
                    - age: integer
                        The age of the staff member in years.
                    - gender: string
                        The gender of the staff member.
                    - birthday: string
                        The date of birth of the staff member.
                    - id: string
                        The unique identification code of the staff member."""
        self.__name = name

        if age < 0 or age > 120:
            raise ValueError("Age must be between 0 and 100")
        self.__age = age

        if gender.lower() not in ["male", "female"]:
            raise ValueError("Gender must be 'male' or 'female'")
        self.__gender = gender

        if not isinstance(birthday, str):
            raise TypeError("Birthday must be a string")

        self.__birthday = birthday
        self.__id = id
        self.__role = None
        self.__tasks = []
        self.__reports = []


    @property
    def id(self):
        """ Returns the unique staff id for this staff member. """
        return self.__id
    @property
    def name(self):
        """ Returns the name of this staff member. """
        return self.__name
    @property
    def age(self):
        """ Returns the age of this staff member. """
        return self.__age
    @property
    def role(self):
        """ Returns the role assigned to this staff member. """
        return self.__role
    @role.setter
    def role(self, role):
        """ Sets the role assigned to this staff member. """
        self.__role = role
        return
    @property
    def tasks(self):
        """ Returns the tasks assigned to this staff member. """
        return self.__tasks
    @tasks.setter
    def tasks(self, tasks):
        """ Sets the tasks assigned to this staff member. """
        self.__tasks = tasks
    @property
    def reports(self):
        """ Returns the reports generated by this staff member. """
        return self.__reports

    def __repr__(self):
        """ Returns a concise string representation used for debugging and internal display. """
        role = "Staff Member" if self.__role is None else self.__role
        return f"ID: {self.__id} | Role: {role}"

    def __str__(self):
        """ Returns a formatted string representation of this staff member, subclasses extend this __str__ method. """
        return f"ID: {self.__id} | Role: {self.__role}"

    def feed_animal(self, animal: Animal):
        """ Allows this staff member to feed an animal object and triggers the animal’s eat behaviour.
            Parameters:
                - animal: Animal
                    The animal object being fed."""

        print(f"{self.__name} is feeding {animal.name}")
        animal.eat()

    def report_issue(self, date: str, summary: str, description: str):
        """ Creates a new issue report authored by this staff member.
            Parameters:
                - date: string
                    The date on which the issue is being reported.
                - summary: string
                    A short summary describing the issue.
                - description: string
                    A detailed description of the issue."""

        new_issue = Issue(self.__name, date, summary, description)
        self.__reports.append(new_issue)

