

MAMMAL_DATA = {
    "Lion": {"class": "mammal", "diet": "carnivore", "enclosure": "Savannah", "min_size": 100, "sound": "roar"},
    "Black Bear": {"class": "mammal", "diet": "carnivore", "enclosure": "Forest", "min_size": 100, "sound": "growl"},
    "Brown Bear": {"class": "mammal", "diet": "carnivore", "enclosure": "Forest", "min_size": 100, "sound": "growl"},
    "Polar Bear": {"class": "mammal", "diet": "carnivore", "enclosure": "Arctic", "min_size": 100, "sound": "huff"},
    "Grizzly Bear": {"class": "mammal", "diet": "carnivore", "enclosure": "Forest", "min_size": 100, "sound": "roar"},
    "Giraffe": {"class": "mammal", "diet": "herbivore", "enclosure": "Savannah", "min_size": 500, "sound": "hum"},
    "Zebra": {"class": "mammal", "diet": "herbivore", "enclosure": "Savannah", "min_size": 500, "sound": "whinny"},
    "Puma": {"class": "mammal", "diet": "herbivore", "enclosure": "Mountain", "min_size": 100, "sound": "growl"},
    "Meerkat": {"class": "mammal", "diet": "herbivore", "enclosure": "Desert", "min_size": 15, "sound": "chirp"},
    "Hippopotamus": {"class": "mammal", "diet": "herbivore", "enclosure": "Wetlands", "min_size": 600, "sound": "grunt"},
    "Rhinoceros": {"class": "mammal", "diet": "herbivore", "enclosure": "Savannah", "min_size": 600, "sound": "snort"},
    "Cheetah": {"class": "mammal", "diet": "carnivore", "enclosure": "Savannah", "min_size": 200, "sound": "chirp"},
    "Leopard": {"class": "mammal", "diet": "carnivore", "enclosure": "Forest", "min_size": 200, "sound": "growl"},
    "Tiger": {"class": "mammal", "diet": "carnivore", "enclosure": "Rainforest", "min_size": 300, "sound": "roar"},
    "Gorilla": {"class": "mammal", "diet": "herbivore", "enclosure": "Rainforest", "min_size": 200, "sound": "hoot"},
    "Chimpanzee": {"class": "mammal", "diet": "omnivore", "enclosure": "Rainforest", "min_size": 150, "sound": "screech"},
    "Orangutan": {"class": "mammal", "diet": "herbivore", "enclosure": "Rainforest", "min_size": 150, "sound": "long call"},
    "Kangaroo": {"class": "mammal", "diet": "herbivore", "enclosure": "Grassland", "min_size": 100, "sound": "thump"},
    "Koala": {"class": "mammal", "diet": "herbivore", "enclosure": "Eucalyptus Forest", "min_size": 50, "sound": "bellow"},
    "Red Panda": {"class": "mammal", "diet": "herbivore", "enclosure": "Mountain Forest", "min_size": 50, "sound": "chirp"},
    "Wolf": {"class": "mammal", "diet": "carnivore", "enclosure": "Forest", "min_size": 150, "sound": "howl"},
    "Hyena": {"class": "mammal", "diet": "carnivore", "enclosure": "Savannah", "min_size": 150, "sound": "cackle"},
    "Bison": {"class": "mammal", "diet": "herbivore", "enclosure": "Grassland", "min_size": 400, "sound": "bellow"},
    "Camel": {"class": "mammal", "diet": "herbivore", "enclosure": "Desert", "min_size": 300, "sound": "grunt"},
    "Llama": {"class": "mammal", "diet": "herbivore", "enclosure": "Mountain", "min_size": 150, "sound": "hum"},
    "Capybara": {"class": "mammal", "diet": "herbivore", "enclosure": "Wetlands", "min_size": 50, "sound": "whistle"},
    "Otter": {"class": "mammal", "diet": "carnivore", "enclosure": "Riverbank", "min_size": 30, "sound": "chirp"},
    "Seal": {"class": "mammal", "diet": "carnivore", "enclosure": "Arctic Pool", "min_size": 100, "sound": "bark"},
    "Sea Lion": {"class": "mammal", "diet": "carnivore", "enclosure": "Coastal Pool", "min_size": 120, "sound": "bark"},
    "Dolphin": {"class": "mammal", "diet": "carnivore", "enclosure": "Aquarium", "min_size": 300, "sound": "click"}
}

REPTILE_DATA = {
    "Cobra": {"class": "reptile", "diet": "carnivore", "enclosure": "tropical terrarium", "min_size": 20},
    "King Cobra": {"class": "reptile", "diet": "carnivore", "enclosure": "tropical terrarium", "min_size": 25},
    "Python": {"class": "reptile", "diet": "carnivore", "enclosure": "tropical terrarium", "min_size": 40},
    "Boa Constrictor": {"class": "reptile", "diet": "carnivore", "enclosure": "tropical terrarium", "min_size": 40},
    "Anaconda": {"class": "reptile", "diet": "carnivore", "enclosure": "aquatic reptile", "min_size": 80},
    "Komodo Dragon": {"class": "reptile", "diet": "carnivore", "enclosure": "tropical terrarium", "min_size": 80},
    "Monitor Lizard": {"class": "reptile", "diet": "carnivore", "enclosure": "tropical terrarium", "min_size": 40},
    "Bearded Dragon": {"class": "reptile", "diet": "omnivore", "enclosure": "desert terrarium", "min_size": 15},
    "Iguana": {"class": "reptile", "diet": "herbivore", "enclosure": "tropical terrarium", "min_size": 25},
    "Chameleon": {"class": "reptile", "diet": "carnivore", "enclosure": "tropical terrarium", "min_size": 10},
    "Gecko": {"class": "reptile", "diet": "carnivore", "enclosure": "desert terrarium", "min_size": 10},
    "Horned Viper": {"class": "reptile", "diet": "carnivore", "enclosure": "desert terrarium", "min_size": 15},
    "Desert Tortoise": {"class": "reptile", "diet": "herbivore", "enclosure": "desert terrarium", "min_size": 30},
    "Giant Tortoise": {"class": "reptile", "diet": "herbivore", "enclosure": "tropical terrarium", "min_size": 60},
    "Crocodile": {"class": "reptile", "diet": "carnivore", "enclosure": "aquatic reptile", "min_size": 200},
    "Alligator": {"class": "reptile", "diet": "carnivore", "enclosure": "aquatic reptile", "min_size": 180},
    "Sea Turtle": {"class": "reptile", "diet": "herbivore", "enclosure": "aquatic reptile", "min_size": 150},
}

BIRD_DATA = {
    "Eagle": {"class": "bird", "diet": "carnivore", "enclosure": "aviary", "min_size": 80},
    "Hawk": {"class": "bird", "diet": "carnivore", "enclosure": "aviary", "min_size": 70},
    "Owl": {"class": "bird", "diet": "carnivore", "enclosure": "aviary", "min_size": 60},
    "Falcon": {"class": "bird", "diet": "carnivore", "enclosure": "aviary", "min_size": 60},
    "Vulture": {"class": "bird", "diet": "carnivore", "enclosure": "aviary", "min_size": 100},
    "Macaw": {"class": "bird", "diet": "herbivore", "enclosure": "tropical aviary", "min_size": 40},
    "Cockatoo": {"class": "bird", "diet": "herbivore", "enclosure": "tropical aviary", "min_size": 35},
    "Toucan": {"class": "bird", "diet": "herbivore", "enclosure": "tropical aviary", "min_size": 30},
    "Flamingo": {"class": "bird", "diet": "omnivore", "enclosure": "waterfowl aviary", "min_size": 80},
    "Pelican": {"class": "bird", "diet": "carnivore", "enclosure": "waterfowl aviary", "min_size": 90},
    "Duck": {"class": "bird", "diet": "omnivore", "enclosure": "waterfowl aviary", "min_size": 40},
    "Swan": {"class": "bird", "diet": "herbivore", "enclosure": "waterfowl aviary", "min_size": 60},
    "Penguin": {"class": "bird", "diet": "carnivore", "enclosure": "waterfowl aviary", "min_size": 100},
    "Peacock": {"class": "bird", "diet": "herbivore", "enclosure": "aviary", "min_size": 50},
    "Crane": {"class": "bird", "diet": "omnivore", "enclosure": "waterfowl aviary", "min_size": 70},
    "Stork": {"class": "bird", "diet": "carnivore", "enclosure": "waterfowl aviary", "min_size": 80},
    "Canary": {"class": "bird", "diet": "herbivore", "enclosure": "aviary", "min_size": 10},
    "Finch": {"class": "bird", "diet": "herbivore", "enclosure": "aviary", "min_size": 10}
}
